### ISSUE TITLE
why use weight.data.t()

### ISSUE THREAD

**Issue by wangce888** [jihunchoi/lsoftmax-pytorch#3]

**Comment by jihunchoi** [comment]
Hi. Sorry for the late reply. I didn't notice that the issue was created.

It's been a while since I implemented the code, but as far as I remember, the reason for using `weight.data.t()` in weight initialization is to make it compatible to the PyTorch's `nn.Linear`.
PyTorch's `nn.Linear` internally has a weight matrix whose shape is `(out_features, in_features)`, however `weight` matrix in this repo's implementation has the shape of `(in_features, out_features)`.
Since `kaiming_normal` initializer considers fan-in or fan-out values of a weight matrix, I transposed the `weight` matrix before giving it to `init.kaiming_normal`.
